# 1. Use Node to build the app
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
# RUN npm run build
RUN DATABASE_URL=file:dummy.db npm run build

# 2. Use a clean Node image to run the app
FROM node:20-alpine
WORKDIR /app
# Ensure the SQLite folder exists
RUN mkdir -p /app/data

COPY --from=builder /app/build build/
COPY --from=builder /app/node_modules node_modules/
COPY package.json .

# Copy migration files (generated by db:generate)
COPY drizzle drizzle/

# Copy config so migrate knows where to find migrations
COPY drizzle.config.js ./

COPY src/lib/server/db/schema.js src/lib/server/db/schema.js

EXPOSE 3000
ENV NODE_ENV=production

# Run migrations, THEN start app
CMD ["sh", "-c", "npm run db:migrate && node build"]
